stages:
  download_nltk:
    cmd: python3 scripts/download_nltk_data.py
    outs:
      - nltk_data

  preprocess:
    cmd: python3 src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/sentiment_data.csv
      - config/config.yaml
      - nltk_data
    outs:
      - data/processed

  log_eda:
    cmd: python3 src/data/log_eda_mlflow.py
    deps:
      - src/data/log_eda_mlflow.py
      - data/processed/eda/missing_values.png
      - data/processed/eda/class_distribution.png
      - data/processed/eda/common_words.png
      - data/processed/eda/wordcloud.png
      - config/config.yaml

  baseline:
    cmd: python3 src/models/baseline.py
    deps:
      - src/models/baseline.py
      - data/processed/train.csv
      - data/processed/test.csv
      - config/config.yaml
      - params.yaml
