data:
  raw: data/sentiment_data.csv
  processed: data/processed
  nltk_data: nltk_data
  columns:
    text: Comment
    sentiment: Sentiment
  eda_dir: data/processed/eda

mlflow:
  tracking_uri: mlruns
  experiments:
    eda: eda
    baseline: baseline
    bert: bert_finetuning
    lstm: lstm_training

aws:
  bucket_name: your-bucket-name
  prefix: your-prefix 