data:
  raw: data/sentiment_data.csv
  processed: data/processed
  nltk_data: nltk_data
  columns:
    text: Comment
    sentiment: Sentiment
  eda_dir: data/processed/eda

mlflow:
  tracking_uri: "https://dagshub.com/mirambika00/sentiment-analysis-workflow.mlflow/"
  experiments:
    eda: eda
    baseline: baseline_0
